version: "3.9"
services:
  elastic:
    image: amazon/opendistro-for-elasticsearch:1.13.3
    container_name: elastic
    environment:
      - cluster.name=elastic-cluster
      - node.name=elastic
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./config/certificates/wildcard.pem:/usr/share/elasticsearch/config/wildcard.pem
      - ./config/certificates/wildcard.key:/usr/share/elasticsearch/config/wildcard.key
      - ./config/certificates/kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      - ./config/certificates/kirk.key:/usr/share/elasticsearch/config/kirk.key
      - ./config/certificates/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/securityconfig/config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./config/securityconfig/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./config/securityconfig/nodes_dn.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/nodes_dn.yml
      - ./config/securityconfig/roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      elastic:
        aliases:
          - elastic.development.com
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:latest
    container_name: kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://elastic:9200
      ELASTICSEARCH_HOSTS: https://elastic:9200
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/kibana/config/wildcard.key
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/wildcard.pem
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./config/certificates/wildcard.pem:/usr/share/kibana/config/wildcard.pem
      - ./config/certificates/wildcard.key:/usr/share/kibana/config/wildcard.key
      - ./config/certificates/root-ca.pem:/usr/share/kibana/config/root-ca.pem
    networks:
      - elastic

volumes:
  elastic-data:

networks:
  elastic:
